/**:
  ros__parameters:
    aabb_obstacle_centers:
      '0':
        x: 0.0
        y: 0.0
        z: 0.875
      '1':
        x: -0.725
        y: 0.0
        z: 0.425
      '2':
        x: 0.725
        y: 0.0
        z: 0.425
    aabb_obstacle_dims:
      '0':
        x: 1.5
        y: 0.2
        z: 0.05
      '1':
        x: 0.05
        y: 0.1
        z: 0.85
      '2':
        x: 0.05
        y: 0.1
        z: 0.85
    aabb_obstacles:
    - aabb_obstacle0
    - aabb_obstacle1
    - aabb_obstacle2
    cylinder_obstacle_centers:
      '0':
        x: 0.0
        y: -0.35
        z: 0.525
      '1':
        x: 0.0
        y: -0.35
        z: 0.275
    cylinder_obstacle_heights:
    - 0.05
    - 0.55
    cylinder_obstacle_radii:
    - 0.15
    - 0.025
    cylinder_obstacles:
    - cylinder_obstacle0
    - cylinder_obstacle1
    eef_end:
    - 1.0
    - 0.0
    - 1.0874000000000001
    eef_start:
    - -1.0
    - 0.0
    - 1.0874000000000001
    final_positions:
      base_x: 1.4
      base_y: 0.05
      eef_spherical_x: 0.0
      eef_spherical_y: 0.0
      eef_spherical_z: 0.0
      elbow_flex: 1.2041286731793477
      shoulder_lift: 1.344696865251302
      shoulder_pan: -3.0172376590430314
      shoulder_roll: -1.120608226685232e-18
    final_theta: 0.01
    final_x_b:
    - 1.4
    - 0.05
    - 0.6438
    final_x_e:
    - 1.0
    - -7.83773951454306e-17
    - 1.0874000000000001
    final_x_w:
    - 1.3087967932483255
    - 0.03859959915604068
    - 1.0433647706427687
    forearm_length: 0.3143
    initial_positions:
      base_x: -1.4
      base_y: 0.05
      eef_spherical_x: 0.0
      eef_spherical_y: 0.0
      eef_spherical_z: 0.0
      elbow_flex: 1.2041286731793477
      shoulder_lift: 1.344696865251302
      shoulder_pan: -0.12435499454676159
      shoulder_roll: -3.915036581051888e-33
    initial_theta: 0.01
    initial_x_b:
    - -1.4
    - 0.05
    - 0.6438
    initial_x_e:
    - -1.0
    - 0.0
    - 1.0874000000000001
    initial_x_w:
    - -1.3087967932483255
    - 0.03859959915604069
    - 1.0433647706427687
    num_paths: 3
    upperarm_length: 0.41
