/**:
  ros__parameters:
    eef_end:
    - 1.0
    - 0.0
    - 0.5
    eef_start:
    - -1.0
    - 0.0
    - 0.5
    final_positions:
      base_x: 1.0
      base_y: 0.1
      eef_spherical_x: 0.0
      eef_spherical_y: 0.0
      eef_spherical_z: 0.0
      elbow_flex: -1.5291175943723192
      shoulder_lift: 0.8674573622841626
      shoulder_pan: 1.5707963267948966
      shoulder_roll: 0.0
    final_theta: 1.5707963267948966
    final_x_b:
    - 1.0
    - 0.1
    - 0.0
    final_x_e:
    - 1.0
    - 0.0
    - 0.5
    final_x_w:
    - 1.0
    - 0.294030361697727
    - 0.2288060723395453
    forearm_length: 0.4
    initial_positions:
      base_x: -1.0
      base_y: 0.1
      eef_spherical_x: 0.0
      eef_spherical_y: 0.0
      eef_spherical_z: 0.0
      elbow_flex: -1.5291175943723192
      shoulder_lift: 0.8674573622841626
      shoulder_pan: 1.5707963267948966
      shoulder_roll: 0.0
    initial_theta: -1.5707963267948966
    initial_x_b:
    - -1.0
    - 0.1
    - 0.0
    initial_x_e:
    - -1.0
    - 0.0
    - 0.5
    initial_x_w:
    - -1.0
    - 0.294030361697727
    - 0.2288060723395453
    num_paths: 4
    sphere_obstacle_centers:
      '0':
        x: 0.5
        y: 0.0
        z: 0.0
      '1':
        x: -0.5
        y: 0.0
        z: 0.0
    sphere_obstacle_radii:
    - 0.25
    - 0.25
    sphere_obstacles:
    - sphere_obstacle0
    - sphere_obstacle1
    upperarm_length: 0.3
