# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - mobile_manipulator_controller

  mobile_manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_x
      - base_y
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
    action_ns: follow_joint_trajectory
    default: true
